
server:
  port: 8080

  ssl:
    key-store-type: JKS

    key-store: classpath:keystore.jks
  # The password used to generate the certificate
    key-store-password: bilibili
  # The alias mapped to the certificate

spring:
  data:
    mongodb:
      database: fundmanager

  servlet:
    multipart:
      max-file-size: 500KB
      max-request-size: 500KB

miniprogram:
  secret: 3b14abc0ecbb915fdabbee2a8b3e6d31
  appid: wx775176a92e70cee0
  login-url: https://api.weixin.qq.com/sns/jscode2session?appid={appid}&secret={secret}&js_code={code}&grant_type=authorization_code

---
spring:
  profiles: dev

image:
  path: C:\Users\jayso\PycharmProjects\fundmanager\images\full

logging:
  level:
    root: info

---
spring:
  profiles: dep

image:
  path: /home/ubuntu/fundmanager/images/full
